name: mf_env
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.10.5=h4c7d964_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.51.0=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.5.4=h725018a_0
  - pip=25.2=pyh8b19718_0
  - python=3.12.12=h0159041_1_cpython
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h2c6b04d_2
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - flexcache==0.3
      - flexparser==0.4
      - fonttools==4.60.1
      - fuzzywuzzy==0.18.0
      - h5py==3.15.1
      - idna==3.11
      - igraph==1.0.0
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - molesq==0.4.0
      - morphops==0.1.13
      - navis==1.10.0
      - ncollpyde==0.19.0
      - networkx==3.5
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pint==0.25.2
      - platformdirs==4.5.0
      - pykdtree==1.4.3
      - pynrrd==1.1.3
      - pyparsing==3.2.5
      - pypng==0.20220715.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rdata==1.0.0
      - requests==2.32.5
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - six==1.17.0
      - skeletor==1.3.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - trimesh==4.9.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - xarray==2025.10.1
prefix: C:\Users\Katja\miniforge3\envs\mf_env
